# Generated by Django 3.1.3 on 2020-11-14 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for package', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for package', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.TextField(help_text='link at server', max_length=1000)),
                ('link_to_res', models.TextField(help_text='link at server', max_length=1000)),
                ('status', models.CharField(blank=True, choices=[('s', 'Submitted'), ('w', 'Waiting in queue'), ('p', 'In progress'), ('r', 'Ready')], default='s', help_text='Status', max_length=1)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.author')),
            ],
        ),
    ]
